feat: add Raspberry Pi System overview dashboard
influxdata/community-templates pull request #191
Opened 2020-09-17 16:33 UTC by ivankudibal

2020-09-18 16:32 UTC, mhall119 requested changes
A couple of changes requested.

Also can you `git mv raspberry-pi/README.md raspberry-pi/readme.md`? We are working to standardize on this naming convention to make integration in the GUI easier.

2020-09-18 16:32 UTC, mhall119 commented on raspberry-pi/README.md
> +- 2 Variables: `bucket` and `linux_host`
These variables are not defined in the template

2020-09-18 16:32 UTC, mhall119 commented on raspberry-pi/raspberry-pi-system.yml
> +          bucket = "telegraf"
Your Flux queries use the `v.bucket` variable, but your Telegraf config is hard-coded to use `telegraf` for the bucket. If you want bucket to be user-selectable the Telegraf config should use an environment variable such as $INFLUX_BUCKET here

2020-09-21 20:46 UTC, mhall119 commented
@ivankudibal this PR still has the old README.md file in it, can you remove it? Otherwise it looks good

2020-10-26 16:18 UTC, ivankudibal commented
All changes were made, can you review and merge%20the%20template,%20pls?

> A couple of changes requested.
> 
> Also can you `git mv raspberry-pi/README.md raspberry-pi/readme.md`? We are working to standardize on this naming convention to make integration in the GUI easier.

done

2020-11-17 15:31 UTC, mhall119 approved these changes

2020-11-17 15:31 UTC, merged