delete cardinality_now
influxdata/community-templates pull request #218
Opened 2020-12-17 19:16 UTC by Anaisdg

deleted:    influxdb2_cardinality_now/img/cardinality-explorer-dashboard2.png
	deleted:    influxdb2_cardinality_now/readme.md
	deleted:    influxdb2_cardinality_now/cardinality_now.yml

2021-01-23 03:35 UTC, timhallinflux commented
@Anaisdg please review merge conflicts?

2021-01-28 18:56 UTC, mhall119 approved these changes

2021-01-28 18:57 UTC, mhall119 requested changes
This needs to be removed from the table in the main README as well

2021-05-06 16:04 UTC, mhall119 approved these changes
LGTM

2021-05-06 16:04 UTC, merged