Add Node.js monitoring and IoT Center dashboard for Node workshop
influxdata/community-templates pull request #234
Opened 2021-02-16 16:24 UTC by devmirek

2021-02-16 18:59 UTC, mhall119 requested changes
See requested changes

2021-02-16 18:59 UTC, mhall119 commented on iot_center/readme.md
> +  - 0 Buckets:
You can remove the bullet point for any resources not included in this template

2021-02-16 18:59 UTC, mhall119 commented on iot_center/iot_center.yml
> +    query: "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(bucket: \"iot_center\",
Since you have a hard coded bucket name of "iot_center", your template should include a Bucket by that name.

2021-02-16 18:59 UTC, mhall119 commented on node_js/readme.md
> +  - 0 Telegraf Configurations:
You don't need to list resources that aren't provided

2021-02-16 18:59 UTC, mhall119 commented on node_js/node_js.yml
> +    query: "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(bucket: \"iot_center\",
Your dashboard queries hard code "iot_center" for the bucket, so your template should include a bucket with that name.

This is the same bucket name as the IoT Center template, should it be using a unique bucket name for the Node.js template?

2021-02-25 11:59 UTC, devmirek commented
All the required changes committed

2021-02-25 14:29 UTC, mhall119 commented
Thanks. All you need to do now is add your templates to the table in the README.md in the root of the repo

2021-03-31 15:13 UTC, merged